# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedto',
            name='sampleID',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Sample'),
        ),
        migrations.AlterField(
            model_name='assignedto',
            name='testID',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Test'),
        ),
        migrations.AlterField(
            model_name='performedby',
            name='technicianID',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Technician'),
        ),
        migrations.AlterField(
            model_name='performedby',
            name='testID',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Test'),
        ),
        migrations.AlterField(
            model_name='receivedby',
            name='sampleID',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Sample'),
        ),
        migrations.AlterField(
            model_name='receivedby',
            name='technicianID',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Technician'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='patientID',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Patient'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='physicianID',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Physician'),
        ),
    ]
