# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170430_0221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'managed': False},
        ),
    ]
