# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170430_0224'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sample',
            table='dashboard_sample',
        ),
    ]
